# Generated by Django 2.0.1 on 2018-07-17 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('delete_ts', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('label', models.CharField(blank=True, max_length=512)),
                ('value', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'db_table': 'blindio_setting',
            },
        ),
    ]
